/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.eb;

import java.beans.Statement;
import java.sql.*;
import java.sql.SQLException;
import static java.util.Collections.emptyList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOD
 */
public class ebUI extends javax.swing.JFrame {

    /**
     * Creates new form ebUI
     */
    public ebUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SearchCriteria = new javax.swing.JLabel();
        srchPriceRB = new javax.swing.JRadioButton();
        srchAgeRB = new javax.swing.JRadioButton();
        srchNameRB = new javax.swing.JRadioButton();
        dispLabel1 = new javax.swing.JLabel();
        dispLabel2 = new javax.swing.JLabel();
        lowerTF = new javax.swing.JTextField();
        upperTF = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        toyList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcodeLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tageGrpLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNameLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tDesLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tPriceLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tQtyLbl = new javax.swing.JLabel();
        buyCB = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        ordQtyTF = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totAmtLbl = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchCriteria.setText("Search Criteria");

        buttonGroup1.add(srchPriceRB);
        srchPriceRB.setText("Price");
        srchPriceRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchPriceRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(srchAgeRB);
        srchAgeRB.setText("Age");
        srchAgeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchAgeRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(srchNameRB);
        srchNameRB.setText("Name");
        srchNameRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchNameRBActionPerformed(evt);
            }
        });

        lowerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerTFActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchBtn.setText("SEARCH IN DATABASE");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(toyList);

        jLabel1.setText("Select Toy below to see it's details");

        jLabel2.setText("Toy Code");

        tcodeLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Age Group");

        tageGrpLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Name");

        tNameLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Description");

        tDesLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Price");

        tPriceLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Qty in Stock");

        tQtyLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buyCB.setText("CLICK ME if you want to buy the toy");
        buyCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyCBActionPerformed(evt);
            }
        });

        jLabel12.setText("Oder Qty");

        ordQtyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordQtyTFActionPerformed(evt);
            }
        });

        confirmBtn.setText("CONFIRM ORDER");
        confirmBtn.setBorder(new javax.swing.border.MatteBorder(null));
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ToyCode", "Name", "Price", "Qty Ordered", "Amout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTbl.setShowHorizontalLines(false);
        orderTbl.setShowVerticalLines(false);
        jScrollPane2.setViewportView(orderTbl);

        jLabel5.setText("ORDER DETAILS ");

        jLabel7.setText("Total Amount Payable (CAD)");

        totAmtLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        submitBtn.setText("SUBMIT");
        submitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("EXIT");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(srchPriceRB)
                                    .addGap(18, 18, 18)
                                    .addComponent(srchAgeRB)
                                    .addGap(30, 30, 30)
                                    .addComponent(srchNameRB))
                                .addComponent(SearchCriteria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dispLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tageGrpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(dispLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(upperTF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tcodeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tDesLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(97, 97, 97)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel10))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tQtyLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ordQtyTF))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(totAmtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buyCB)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(40, 40, 40))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(SearchCriteria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srchPriceRB)
                            .addComponent(srchAgeRB)
                            .addComponent(srchNameRB))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lowerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upperTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(dispLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dispLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(tcodeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tageGrpLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tDesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(tPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(tQtyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buyCB)
                            .addComponent(jLabel12)
                            .addComponent(ordQtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totAmtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(exitBtn))
                .addGap(264, 264, 264))
        );

        SearchCriteria.getAccessibleContext().setAccessibleName("Search Criteria");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lowerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowerTFActionPerformed

    private void buyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyCBActionPerformed
        // TODO add your handling code here:
        if(buyCB.isSelected()){
            ordQtyTF.setEnabled(true);
        }
    }//GEN-LAST:event_buyCBActionPerformed

    private void ordQtyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordQtyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordQtyTFActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        int qtyA = Integer.parseInt(tQtyLbl.getText());
        int qtyO = Integer.parseInt(ordQtyTF.getText());
        if(qtyO > qtyA)
            JOptionPane.showMessageDialog(rootPane, "Only" + qtyA + "items of"+tcodeLbl.getText()+"are in stock!\n SORRY, Cannot take your order.");
        else {
            float amt = qtyO * Float.parseFloat(tPriceLbl.getText());
            float total = Float.parseFloat(totAmtLbl.getText());
            DefaultTableModel model = (DefaultTableModel)orderTbl.getModel();
            int tc = Integer.parseInt(tcodeLbl.getText());
            String qry = "UPDATE toys SET qtyinstock = qtyinstock -" + qtyO + "WHERE toycode =" + tc + ";";
            try{
                Class.forName("java.sql.Driver");
                Connection con  = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "xyz");
                Statement stmt = (Statement) con.createStatement();
                stmt.executeUpdate(qry);
                // now adding to order table
                model.addRow(new Object[]{
                tcodeLbl.getText(), tNameLbl.getText(), tPriceLbl.getText(), ordQtyTF.getText(), amt
            });
                total = total + amt;
                totAmtLbl.setText(""+amt);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error in connectivity.");
            }
            ordQtyTF.setText("");
            ordQtyTF.setEnabled(false);
            buyCB.setSelected(false);
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void srchNameRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchNameRBActionPerformed
        // TODO add your handling code here:
        if(srchNameRB.isSelected()){
            dispLabel1.setText("Enter Name");
            dispLabel2.setEnabled(false);
            upperTF.setEnabled(false);
        }
    }//GEN-LAST:event_srchNameRBActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        emptyList();
        String filter = " ";
        if(srchNameRB.isSelected()){
            filter = "WHERE name = '"+ lowerTF.getText()+ "'";
        }
        else if(srchPriceRB.isSelected()){
            float priceL = Float.parseFloat(lowerTF.getText());
            float priceF = Float.parseFloat(upperTF.getText());
            filter = "WHERE price >=" + priceL +"and price <=" + priceF;
        }
        else if (srchAgeRB.isSelected()){
            int age = Integer.parseInt(lowerTF.getText());
            filter = "WHERE agegrouplowerlimit <="+age  + "and agegroupupperlimit >=" +age;
        }
        int count = 0;
        String query = "SELECT name from toys"+ filter + ";";
        DefaultListModel model;
        model = (DefaultListModel)toyList.getModel();
        try{
            Class.forName("java.sql.Driver");
                Connection con  = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "xyz");
                Statement stmt = (Statement) con.createStatement();
                ResultSet rs;
            rs = stmt.executeQuery(query);
            while(rs.next()){
                model.add(count, rs.getString("name"));
                count++;
            }
            rs.close();
            stmt.close();
            con.close();
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in conectivity");
        }
        ordQtyTF.setEnabled(false);
        
    }//GEN-LAST:event_searchBtnActionPerformed
    
    private void srchAgeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchAgeRBActionPerformed
        // TODO add your handling code here:
        if(srchAgeRB.isSelected()){
            dispLabel1.setText("Enter Name");
            dispLabel2.setEnabled(false);
            upperTF.setEnabled(false);
            
        }
        else {
            dispLabel1.setText("Enter Lower Limit");
            dispLabel2.setEnabled(true);
            upperTF.setEnabled(true );
        }
    }//GEN-LAST:event_srchAgeRBActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Thank you for using the E-Buisness Application.");
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void srchPriceRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchPriceRBActionPerformed
        // TODO add your handling code here:
        if(srchPriceRB.isSelected()){
            dispLabel2.setEnabled(true);
            upperTF.setEnabled(true);
        }
    }//GEN-LAST:event_srchPriceRBActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)orderTbl.getModel();
        int count = model.getRowCount();
        String total = totAmtLbl.getText();
        JOptionPane.showMessageDialog(rootPane, "You have order for" + count + "items \n and your total bill amount is ;"+total);
     
    }//GEN-LAST:event_submitBtnActionPerformed
void emptyList(){
    DefaultListModel model = (DefaultListModel)toyList.getModel();
    while(model.getSize()>0)
    model.remove(0);
}

private void toyListValueChanged(javax.swing.event.ListSelectionEvent evt){
    String selval = (String) toyList.getSelectedValue();
    String query = "SELECT * FROM toys WHERE name ='" + selval + "';";
     try{
            Class.forName("java.sql.Driver");
                Connection con  = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "xyz");
                Statement stmt = (Statement) con.createStatement();
                ResultSet rs;
            rs = stmt.executeQuery(query);
            rs.next();
            {
                tcodeLbl.setText(""+ rs.getInt(1));
                tNameLbl.setText(rs.getString(2));
                tDesLbl.setText(rs.getString(3));
                tQtyLbl.setText(""+rs.getInt(4));
                tageGrpLbl.setText(""+ rs.getInt(5) + "to" + rs.getInt(6));
                tPriceLbl.setText(""+ rs.getFloat(8));
            }
            rs.close();
            stmt.close();
            con.close();
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in conectivity");
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ebUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ebUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ebUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ebUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ebUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SearchCriteria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox buyCB;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel dispLabel1;
    private javax.swing.JLabel dispLabel2;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lowerTF;
    private javax.swing.JTextField ordQtyTF;
    private javax.swing.JTable orderTbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JRadioButton srchAgeRB;
    private javax.swing.JRadioButton srchNameRB;
    private javax.swing.JRadioButton srchPriceRB;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel tDesLbl;
    private javax.swing.JLabel tNameLbl;
    private javax.swing.JLabel tPriceLbl;
    private javax.swing.JLabel tQtyLbl;
    private javax.swing.JLabel tageGrpLbl;
    private javax.swing.JLabel tcodeLbl;
    private javax.swing.JLabel totAmtLbl;
    private javax.swing.JList toyList;
    private javax.swing.JTextField upperTF;
    // End of variables declaration//GEN-END:variables
}
